language: objective-c
install: true
env:
  matrix:
    - XCODE_SCHEME=libPusher
    - XCODE_SCHEME=libPusher-OSX
script: xctool -workspace libPusher.xcworkspace -scheme $XCODE_SCHEME -sdk iphonesimulator build test
